<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>_123ISIP_Prokofiev_UP</RootNamespace>
    <AssemblyName>123ISIP_Prokofiev_UP</AssemblyName>
    <LangVersion>latest</LangVersion>
    <AppDesignerFolder>Properties</AppDesignerFolder>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Data" />
    <Reference Include="System.Configuration" />
  </ItemGroup>

</Project>
